Eu 009
FacuNBustos/grupo-n-7 pull request #12
Opened 2022-11-03 22:43 UTC by Agustinf90

AS: Development
I Want: add the endpoint to create users
To: complete the ticket EU-009

![evidence00901](https://user-images.githubusercontent.com/88116635/199848026-40075484-970c-4f83-9db2-c0432596f0ce.png)
![evidence00902](https://user-images.githubusercontent.com/88116635/199848025-6ef70aa2-8d55-4012-912f-98c843c5e3eb.png)
![evidence00907](https://user-images.githubusercontent.com/88116635/199848016-a7a1535b-91e4-40de-ac91-9b469e0dbcb4.png)
![evidence00906](https://user-images.githubusercontent.com/88116635/199848021-83a15fe3-f622-4fb3-8c35-bf091623beb5.png)
![evidence00905](https://user-images.githubusercontent.com/88116635/199848022-aa021af6-f88b-42ad-a0b4-b152aea8cd0b.png)
![evidence00904](https://user-images.githubusercontent.com/88116635/199848023-6cfa1aa9-18d2-4567-b0b8-5a3f07e87c49.png)
![evidence00903](https://user-images.githubusercontent.com/88116635/199848024-e82a1ffe-032a-4f85-a530-70e79cdce293.png)

2022-11-03 23:32 UTC, cristdales requested changes

2022-11-03 23:32 UTC, cristdales commented on controllers/users/create.user.js
> +          'password',
La password hasheada se tiene que sacar de la respuesta al cliente.

2022-11-04 15:49 UTC, cristdales requested changes
Habría que sacar el package.json y package-lock.json del PR porque van a dar conflictos. El bcrypt ya está añadido en dev.

2022-11-04 20:21 UTC, Agustinf90 commented
dale ahí veo lo de la ruta, se debe haber pisado con otros prs

2022-11-05 17:01 UTC, FacuNBustos requested changes
Fíjate que en la ultima corrección, dejarte los headers de git al solventar el error de merge

2022-11-05 18:28 UTC, cristdales commented
> Fíjate que en la ultima corrección, dejarte los headers de git al solventar el error de merge

Si fijate que git te deja las 2 versiones con un separador. Tenés que arreglarlo a mano

2022-11-05 19:20 UTC, Agustinf90 commented
Bien no me dí cuenta

2022-11-05 19:45 UTC, FacuNBustos approved these changes

2022-11-05 20:40 UTC, adriangonzalez-dev approved these changes

2022-11-05 20:54 UTC, merged