EC-021
FacuNBustos/grupo-n-7 pull request #29
Opened 2022-11-05 23:29 UTC by khuaza9612

## Trello Ticket

- [EC-021](https://trello.com/c/mWwe0zOr/26-ec-021-endpoint-para-editar-categor%C3%ADas)

## Description
AS:edit category
I Want:A PUT request must be made

## Evidence:

![prueba 5](https://user-images.githubusercontent.com/90488670/200146734-4c862e4e-23d3-4e2f-9433-f00aaf2d3c35.png)

2022-11-06 00:01 UTC, FacuNBustos commented
Por favor, poner un titulo mas descriptivo en la PR

2022-11-06 00:04 UTC, FacuNBustos requested changes
El usuario también debería poder cambiar la descripción de category de ser requerido.

2022-11-06 00:39 UTC, khuaza9612 commented
![image](https://user-images.githubusercontent.com/90488670/200148667-28e39c75-24d8-4087-a5e4-03b7e4e87faf.png)
![image](https://user-images.githubusercontent.com/90488670/200148673-b2ba0da2-6de2-4763-8a52-89a0beccb9aa.png)
ya modifica la description

2022-11-06 01:29 UTC, cristdales requested changes

2022-11-06 01:29 UTC, cristdales commented on schemas/categories/update.schema.js
> +      optional: false,
en la actualización, no es obligatorio cambiarle el nombre.

2022-11-06 12:48 UTC, cristdales commented
En el schema:

2022-11-07 16:54 UTC, cristdales approved these changes

2022-11-07 16:56 UTC, FacuNBustos approved these changes

2022-11-07 17:17 UTC, merged